server:
  port: 8087
spring:
  application:
    name: stream-rocketmq
  cloud:
    stream:
      rocketmq:
        binder:
          # 配置rocketmq的nameserver地址
          namesrv-addr: 127.0.0.1:9876
      bindings:
        # 定义name为output的binding
        output:
          destination: test-topic
          content-type: application/json
          group: test-producer-group2
          tag: test-tag
        #定义name为input的binding
        input:
          destination: test-topic
          content-type: application/json
          group: test-group
#开启endpoint
management:
  endpoint:
    health:
      show-details: always
      enabled: true
